export const TENANT_ANNOUNCEMENTS = {
  QUERY_KEY: "tenant-announcements",
  PAGE_TITLE: "Announcements",
  PAGE_DESCRIPTION: "View important announcements from your PG management",
  SEARCH_PLACEHOLDER: "Search announcements...",
  NO_RESULTS_TITLE: "No announcements found",
  NO_RESULTS_DESC: "Try adjusting your search query",
  EMPTY_STATE_TITLE: "No announcements yet",
  EMPTY_STATE_DESC: "You'll see important announcements from your PG management here",
  DATE_FORMAT: "MMM dd, yyyy 'at' h:mm a",
  PRIORITY: {
    HIGH: "high",
    MEDIUM: "medium",
    LOW: "low",
  },
} as const;

export const PRIORITY_ORDER: Record<string, number> = {
  [TENANT_ANNOUNCEMENTS.PRIORITY.HIGH]: 0,
  [TENANT_ANNOUNCEMENTS.PRIORITY.MEDIUM]: 1,
  [TENANT_ANNOUNCEMENTS.PRIORITY.LOW]: 2,
};

export const TENANT_COMPLAINTS = {
  QUERY_KEY: "tenant-complaints",
  PAGE_TITLE: "My Complaints",
  PAGE_SUBTITLE: "Track and manage your requests",
  BUTTON_CREATE: "Submit New Complaint",
  DIALOG_TITLE: "Submit Complaint",
  DIALOG_DESC: "Report an issue or request maintenance",
  LABEL_TITLE: "Issue Title",
  PLACEHOLDER_TITLE: "e.g., Fan not working",
  LABEL_DESCRIPTION: "Description",
  PLACEHOLDER_DESCRIPTION: "Describe the issue in detail...",
  LABEL_PRIORITY: "Priority",
  PRIORITY_LOW: "Low Priority",
  PRIORITY_MEDIUM: "Medium Priority",
  PRIORITY_HIGH: "High Priority",
  BUTTON_SUBMIT: "Submit Complaint",
  BUTTON_SUBMITTING: "Submitting...",
  EMPTY_TITLE: "No Complaints Yet",
  EMPTY_DESC: "You haven't submitted any complaints or maintenance requests",
  EMPTY_FOOTER: "Click the button above to submit your first complaint",
  TOAST_SUCCESS: "Complaint submitted successfully",
  TOAST_ERROR: "Failed to create complaint",
  STATUS_OPEN: "Open",
  STATUS_IN_PROGRESS: "In Progress",
  STATUS_RESOLVED: "Resolved",
  RESOLUTION_TITLE: "Resolution",
  RESOLVED_ON: "Resolved on",
} as const;